SnakeTn\CatalogPromotion\Entity\PromotionAction:
  type: entity
  table: catalog_promotion_action
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    type:
      type: string
      length: 255
    configuration:
      type: json_array
  manyToOne:
    promotion:
      targetEntity: SnakeTn\CatalogPromotion\Entity\Promotion
      inversedBy: actions
